### PR TITLE
llm-numbers-cn

### PR DESCRIPTION
**Pull request by w-tz**
We added a Chinese version of llm-numbers.

### CODE REVIEW

**Comment by woshiyyya** [comment]
Hi @w-tz , thank you for your efforts to translate this blog to Chinese. I have polished the relevant expressions and fixed several typos in this PR. 

Please take a look: https://github.com/NascentCore/llm-numbers-cn/pull/9

**Review by woshiyyya — CHANGES_REQUESTED** [review]
Hi @w-tz , thank you for your efforts to translate this blog to Chinese. I fixed some typos and polished the wordings with more accurate expressions.

Please take a look: https://github.com/NascentCore/llm-numbers-cn/pull/9

**Comment by w-tz** [comment]
> Hi @w-tz , thank you for your efforts to translate this blog to Chinese. I fixed some typos and polished the wordings with more accurate expressions.
> 
> Please take a look: [NascentCore/llm-numbers-cn#9](https://github.com/NascentCore/llm-numbers-cn/pull/9)



> Hi @w-tz , thank you for your efforts to translate this blog to Chinese. I fixed some typos and polished the wordings with more accurate expressions.
> 
> Please take a look: [NascentCore/llm-numbers-cn#9](https://github.com/NascentCore/llm-numbers-cn/pull/9)

Thanks a lot! We have updated it!

**Comment by w-tz** [comment]
> Hi @w-tz , thank you for your efforts to translate this blog to Chinese. I fixed some typos and polished the wordings with more accurate expressions.
> 
> Please take a look: [NascentCore/llm-numbers-cn#9](https://github.com/NascentCore/llm-numbers-cn/pull/9)

Thanks a lot! We have updated it!

**Comment by w-tz** [comment]
Do you have other suggestions?

**Comment by waleedkadous** [comment]
Thank you for your efforts. Change merged.

**Pull request merged**
